DROP DATABASE IF EXISTS say_app;
CREATE DATABASE say_app;
USE say_app;
CREATE TABLE article (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id),
    createdDate DATETIME NOT NULL,
    modifiedDate DATETIME NOT NULL,
    title VARCHAR(100) NOT NULL,
    `body` TEXT NOT NULL,
    isBlind BIT(1) NOT NULL DEFAULT 0
)